### ISSUE TITLE
2-2 fizzbuzz

### ISSUE THREAD

**Issue by lsiedlaczek** [Gralath/EloquentJS#2]
na wstepie:
. przerob to prosze na funkcje, ktora bedzie mogla przyjmowac dowolna liczbe koncowa
. postaraj sie tak przepisac warunki, zeby byly tylko 2 ify (bez zadnego else)

zeby osiagnac punkt drugi dam Ci pare podpowiedzi:
. zrob tylko jeden punkty wyjscia, tzn tylko jeden console.log() na iteracje petli
. console.log(wyrazenie) wyrzuca do konsoli wartosc wyrazenia, tzn jezeli zamiast wyrazenie wstawisz 2 + 3 wypisze Ci 5, wyrazenie = 'a' + 'b' => 'ab', wyrazenie = 3 > 2 => true
. operator || (OR) w javascriptcie dziala tak, ze x || y:
a) jezeli x jest prawdziwe - zwraca x
b) jezeli x jest falszywe - zwraca y
. przeczytaj jakie wartosci sa falsy w jsie: http://ferrante.pl/frontend/javascript/falsy-values-i-operatory-porownania/

**Comment by Gralath** [comment]
Przerobione.

Dzieki za te wszystkie komentarze i informacje, do jutra pewnie pozmieniam te wszystkie zadania.
